server:
  port: 9001

spring:
  application:
    name: NOTEBOOK-SERVICE

eureka:
  client:
    register-with-eurek: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost