server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: NOTEBOOK-SERVICE
          uri: lb://NOTEBOOK-SERVICE
          predicates:
            - Path=/notebook/**

eureka:
  client:
    register-with-eurek: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost